name: Run CI when ci.yml changes

on:
  push:
    paths:
      - .github/workflows/ci-test.yml
  pull_request:
    paths:
      - .github/workflows/ci-test.yml

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade xraybinaryorbit
        pip install pytest>=6.0 #pytest-xvfb
        pip install -r requirements.txt

    - name: Clear pytest cache
      run: pytest --rootdir=./test/ -cache-clear    

    - name: Run tests with Xvfb
      run: pytest --rootdir=./test/ --verbose --junitxml=pytest_results.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: pytest_results.xml

