name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # Valid Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated action

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated action
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pytest
        pip install -r requirements.txt
        pip install .

    - name: Run tests
      run: |
        pytest 

